---
# tasks file for server.firewall

- apt: update_cache=yes cache_valid_time=3600

- name: Install list of packages
  apt: name={{item}} state=installed
  with_items:
       - "iptables-persistent"

- template: src=etc/iptables/rules.j2 dest=/etc/iptables/rules.{{item}}
  with_items:
    - "{{v4}}"
    - "{{v6}}"
  notify: reload netfilter-persistent

- service:
    name: netfilter-persistent
    state: started
    enabled: yes

