---
# tasks file for server.firewall

- apt: update_cache=yes cache_valid_time=3600

- name: Install list of packages
  apt: name={{item}} state=installed
  with_items:
       - "iptables-persistent"

- debconf: name='iptables autosave v4' question='iptables-persistent/autosave_v4' value='true' vtype='boolean'
- debconf: name='iptables autosave v6' question='iptables-persistent/autosave_v6' value='true' vtype='boolean'


- template: src=roles/server.firewall/templates/etc/iptables/rules dest=/etc/iptables/rules.{{item}} 
  with_items:
    - "{{v4}}"
    - "{{v6}}"
  notify: reload netfilter-persistent

- service:
    name: netfilter-persistent
    state: started
    enabled: yes

